name: 'My first github action'

on: [ 'push', 'pull_request' ]

jobs:
  first-job:
    name: 'first job'

    runs-on: ubuntu-latest

    steps:
    - name: output value 1
      id: first
      shell: bash
      run: |
        echo "Hello World 1"

    - name: output value 2
      id: second
      shell: bash
      run: |
        echo "Hello World 2"

  second-job:
    name: 'second job'
    needs: first-job

    runs-on: ubuntu-latest

    steps:
    - name: output value
      id: first
      shell: bash
      run: |
        echo "Hello World 3"

  third-job:
    name: 'third job'
    needs: second-job

    runs-on: ubuntu-latest

    steps:
    - name: output value
      id: first
      shell: bash
      run: |
        echo "Hello World 4"
